name: Build

on:
  push:
    branches-ignore:
      - master
      - feature/*
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"
  
  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Display .NET version
        run: dotnet --version

      - name: Restore solution
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Test solution
        run: dotnet test --no-build --configuration Release

      - name: Publish solution
        if: ${{ inputs.build-artifacts == true }}
        run: |
          dotnet publish --configuration Release --output ./publish
          cd publish
          zip -r ./publish.zip .
        working-directory: ./src/MathHub.Api/

      - name: Upload website artifact (website)
        if: ${{ inputs.build-artifacts == true }}
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./src/MathHub.Api/publish/publish.zip
          if-no-files-found: error