name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.scripts/**'
      - '.github/CODEOWNERS'
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.scripts/**'
      - '.github/CODEOWNERS'
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release
