name: Build

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.scripts/**'
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md
  workflow_call:
    inputs:
      inputName:
        type: string
        required: false
        default: "default name"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget
      
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Print
      run: echo ${{ inputs.inputName }}