name: CICD

on:
  push:
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

env:
    DEPLOY_APP: ${{ startsWith( github.ref_name, feature/ ) || github.ref_name == master }}

jobs:
  
  prepare:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display DEPLOY_APP
        run:
          echo ${{ env.DEPLOY_APP }}
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: ${{ env.DEPLOY_APP }}
    
  deploy:
    if: ${{ env.DEPLOY_APP }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Display env.DEPLOY_APP
        run:
          echo Deploying...
    