name: CICD

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

permissions:
  id-token: write
  contents: read
        
jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  display:
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      - name: Display variable
        run:
          echo ${{ var.AZURE_WEBAPP_NAME }}
        
      - name: Display secret
        run:
          echo ${{ secrets.AZURE_PUBLISH_PROFILE }}
  
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [ display ]
    with:
      environmentName: Development