name: CICD

on:
  push:
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md
  branch_protection_rule:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: ${{ startsWith( github.ref_name, 'feature/' ) || github.ref_name == 'master' }}
    
  deploy:
    needs: [ build ]
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environmentName: Development
    