name: CICD

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.scripts/**'
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml

  deploy-development:
    uses: ./.github/workflows/deploy.yml
    needs: [ build ]