name: CI/CD Feature

on:
  push:
    branches:
      - "feature/**"
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true

  deploy-feature:
    if: ${{ startsWith(github.ref_name, 'feature/') }}
    uses: ./.github/workflows/deploy-feature.yml
    needs: [ build ]
    secrets: inherit
