name: CICD

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

permissions:
  id-token: write
  contents: read
        
jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [ build ]
    secrets: inherit
    with:
      environmentName: Development