name: CICD

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

#permissions:
#  id-token: write
#  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      inputName: "value from cicd"

#  deploy-development:
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    needs: [ build ]
#    with:
#      environmentName: Development
#
#  deploy-staging:
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    needs: [ deploy-development ]
#    with:
#      environmentName: Staging
#
#  deploy-production:
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    needs: [ deploy-staging ]
#    with:
#      environmentName: Production