name: CICD

on:
  push:
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md


jobs:
  
  prepare:
    runs-on: ubuntu-latest
    env:
      DEPLOY_APP: ${{ startsWith( github.ref_name, 'feature/' ) || github.ref_name == 'master' }}
    
    steps:
      - name: Display DEPLOY_APP
        run:
          echo ${{ env.DEPLOY_APP }}
  
  build:
    needs: [ prepare ]
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: ${{ startsWith( github.ref_name, 'feature/' ) || github.ref_name == 'master' }}
    
  deploy:
    needs: [ build ]
    if: ${{ startsWith( github.ref_name, 'feature/' ) || github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Display env.DEPLOY_APP
        run:
          echo Deploying...
    