name: CI/CD Default

on:
  push:
    branches-ignore:
      - "master"
      - "feature/**"
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: false
