name: CICD

on:
  push:
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: ${{ github.ref_name == 'master' }}
  
  deploy-development:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy.yml
    needs: [ build ]
    secrets: inherit
    with:
      environmentName: Development
  
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    needs: [ deploy-development ]
    secrets: inherit
    with:
      environmentName: Staging
  
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: [ deploy-staging ]
    secrets: inherit
    with:
      environmentName: Production