name: CICD

on:
  push:
    paths-ignore:
      - ".github/CODEOWNERS"
      - .gitignore
      - "**/*.md"

permissions:
  id-token: write
  contents: read
    
jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  deploy-development:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy.yml
    needs: [ build ]
    secrets: inherit
    with:
      environmentName: Development
      
  deploy-feature:
    if: ${{ startsWith( github.ref_name, 'feature/' ) }}
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      - name: Deploy feature
        run:
            echo deploy feature...
  
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    needs: [ deploy-development ]
    secrets: inherit
    with:
      environmentName: Staging
  
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: [ deploy-staging ]
    secrets: inherit
    with:
      environmentName: Production