name: deploy-staging

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mathhub-staging

jobs:
  
  build:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STAGING_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip