name: Deploy

on:
  workflow_call: 
    inputs: 
      environmentName:
        type: string
        required: true

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip