name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

env:
  MASTER_AZURE_WEBAPP_NAME: mathhub-master
  STAGING_AZURE_WEBAPP_NAME: mathhub-master
  AZURE_WEBAPP_PACKAGE_PATH: ./publish

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  deploy-master:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.MASTER_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DEVELOPMENT_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip
          
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [ deploy-master ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.STAGING_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STAGING_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip