name: Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  
  deply-development:
    if: ${{ inputs.environmentName == 'Development' }}
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: mathhub-master
      AZURE_WEBAPP_PACKAGE_PATH: ./publish

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DEVELOPMENT_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip