name: deploy

on:
  workflow_call: 
    inputs: 
      azureWebAppName:
        type: string
        required: true
      publishProfile:
        type: string
        required: true

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display app name
        run:
          echo ${{ inputs.azureWebAppName }}

      - name: Display publish profile
        run:
          echo ${{ inputs.publishProfile }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.azureWebAppName }}
          publish-profile: ${{ inputs.publishProfile }}
          package: website/publish.zip