name: deploy

on:
  workflow_call: 
    inputs: 
      environmentName:
        type: string
        required: true

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display web app name
        run:
          echo ${{ vars.AZURE_WEBAPP_NAME }}

      - name: Display publish profile
        run:
          echo ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip