name: deploy-development

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: Development

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip