name: Development CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

env:
  AZURE_WEBAPP_NAME: mathhub-master
  AZURE_WEBAPP_PACKAGE_PATH: ./publish

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: false
  
#  publish:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - name: Deployment
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.DEVELOPMENT_AZURE_PUBLISH_PROFILE }}
#          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"