name: Feature Deploy

on:
  push:
    branches:
      - feature/*
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
  
  prepare:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display message
        run:
          echo Hello from feature