name: Production Deployment 🚀

on:
  workflow_dispatch:
    branches:
      - master
  workflow_run:
    workflows: [ "Development Deployment 🚀" ]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: mathhub-production
  AZURE_WEBAPP_PACKAGE_PATH: ./publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore ./MathHub.sln

      - name: Build
        run: dotnet build ./MathHub.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/MathHub.Api/MathHub.Api.csproj --configuration Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PRODUCTION_AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"