name: Staging Deploy

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mathhub-staging

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STAGING_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip