name: Staging Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Manually approve the job'
        type: boolean
        required: false
        default: false

env:
  AZURE_WEBAPP_NAME: mathhub-staging

jobs:
  
  deploy-development:
    uses: ./.github/workflows/development-deploy.yml
  
  deploy-staging:
    if: github.event.inputs.manual_approval == true
    runs-on: ubuntu-latest
    needs: [ deploy-development ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STAGING_AZURE_PUBLISH_PROFILE }}
          package: website/publish.zip